# Dockerfile.gateway
FROM nginx:alpine

# 1. Remove the default Nginx config
RUN rm /etc/nginx/conf.d/default.conf

# 2. Copy your AWS Main Config
# This uses the exact same config file that AWS uses
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]